language: python
python:
#  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
  - "pypy"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
addons:
  sonarcloud:
    organization: "AlienVaultPyEx2_W"
# command to run tests
script:
  - python setup.py test
  - coverage run --source AlienVaultPyEx2 setup.py test
  - coverage combine
  - coverage report
  - coverage xml
  - sonar-scanner -Dsonar.projectKey=AlienVaultPyEx2_W -Dsonar.sources=. -Dsonar.organization=thefantasyclub-github -Dsonar.python.coverage.reportPath=coverage.xml -Dsonar.exclusions=coverage.xml,setup.py,versioneer.py,docs/*,tests/*,AlienVaultPyEx2/_*
after_success:
  - coveralls
